es:
  uri: http://elasticsearch-master:9200

serviceMonitor:
  enabled: true

tolerations:
  - key: node-role
    operator: Equal
    value: infra
    effect: NoSchedule

nodeSelector:
  yandex.cloud/node-group-id: catr3qvo662pnad0j4vn
