grafana:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    path: /
    hosts:
      - grafana.51.250.85.229.nip.io
  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki:3100
      jsonData:
        maxLines: 1000

alertmanager:
  alertmanagerSpec:
    tolerations:
      - key: node-role
        operator: Equal
        value: infra
        effect: NoSchedule
    nodeSelector:
      yandex.cloud/node-group-id: catr3qvo662pnad0j4vn

prometheusOperator:
  tolerations:
    - key: node-role
      operator: Equal
      value: infra
      effect: NoSchedule
  nodeSelector:
    yandex.cloud/node-group-id: catr3qvo662pnad0j4vn

  admissionWebhooks:
    patch:
      tolerations:
        - key: node-role
          operator: Equal
          value: infra
          effect: NoSchedule
      nodeSelector:
        yandex.cloud/node-group-id: catr3qvo662pnad0j4vn

prometheus:
  prometheusSpec:
    tolerations:
      - key: node-role
        operator: Equal
        value: infra
        effect: NoSchedule
    nodeSelector:
      yandex.cloud/node-group-id: catr3qvo662pnad0j4vn
